
package sr.puc.server.ws.soap.a5;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonaServiceA5", targetNamespace = "http://a5.soap.ws.server.puc.sr/", wsdlLocation = "https://awshomo.afip.gov.ar/sr-padron/webservices/personaServiceA5?WSDL")
public class PersonaServiceA5_Service
    extends Service
{

    private final static URL PERSONASERVICEA5_WSDL_LOCATION;
    private final static WebServiceException PERSONASERVICEA5_EXCEPTION;
    private final static QName PERSONASERVICEA5_QNAME = new QName("http://a5.soap.ws.server.puc.sr/", "PersonaServiceA5");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://awshomo.afip.gov.ar/sr-padron/webservices/personaServiceA5?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONASERVICEA5_WSDL_LOCATION = url;
        PERSONASERVICEA5_EXCEPTION = e;
    }

    public PersonaServiceA5_Service() {
        super(__getWsdlLocation(), PERSONASERVICEA5_QNAME);
    }

    public PersonaServiceA5_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONASERVICEA5_QNAME, features);
    }

    public PersonaServiceA5_Service(URL wsdlLocation) {
        super(wsdlLocation, PERSONASERVICEA5_QNAME);
    }

    public PersonaServiceA5_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONASERVICEA5_QNAME, features);
    }

    public PersonaServiceA5_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonaServiceA5_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonaServiceA5
     */
    @WebEndpoint(name = "PersonaServiceA5Port")
    public PersonaServiceA5 getPersonaServiceA5Port() {
        return super.getPort(new QName("http://a5.soap.ws.server.puc.sr/", "PersonaServiceA5Port"), PersonaServiceA5.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonaServiceA5
     */
    @WebEndpoint(name = "PersonaServiceA5Port")
    public PersonaServiceA5 getPersonaServiceA5Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://a5.soap.ws.server.puc.sr/", "PersonaServiceA5Port"), PersonaServiceA5.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONASERVICEA5_EXCEPTION!= null) {
            throw PERSONASERVICEA5_EXCEPTION;
        }
        return PERSONASERVICEA5_WSDL_LOCATION;
    }

}
