
package src.sr.puc.server.ws.soap.a5;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonaServiceA5", targetNamespace = "http://a5.soap.ws.server.puc.sr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonaServiceA5 {


    /**
     * 
     * @param cuitRepresentada
     * @param sign
     * @param idPersona
     * @param token
     * @return
     *     returns src.sr.puc.server.ws.soap.a5.PersonaReturn
     */
    @WebMethod
    @WebResult(name = "personaReturn", targetNamespace = "")
    @RequestWrapper(localName = "getPersona", targetNamespace = "http://a5.soap.ws.server.puc.sr/", className = "src.sr.puc.server.ws.soap.a5.GetPersona")
    @ResponseWrapper(localName = "getPersonaResponse", targetNamespace = "http://a5.soap.ws.server.puc.sr/", className = "src.sr.puc.server.ws.soap.a5.GetPersonaResponse")
    public PersonaReturn getPersona(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "sign", targetNamespace = "")
        String sign,
        @WebParam(name = "cuitRepresentada", targetNamespace = "")
        long cuitRepresentada,
        @WebParam(name = "idPersona", targetNamespace = "")
        long idPersona);

    /**
     * 
     * @return
     *     returns src.sr.puc.server.ws.soap.a5.DummyReturn
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dummy", targetNamespace = "http://a5.soap.ws.server.puc.sr/", className = "src.sr.puc.server.ws.soap.a5.Dummy")
    @ResponseWrapper(localName = "dummyResponse", targetNamespace = "http://a5.soap.ws.server.puc.sr/", className = "src.sr.puc.server.ws.soap.a5.DummyResponse")
    public DummyReturn dummy();

}
