/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shoc.controller.Panels;

import com.shoc.controller.Panels.componentes.IValidable;
import com.shoc.controller.Panels.componentes.RequiredTextfield;
import com.shoc.domain.DispositivosEnum;
import com.shoc.domain.IObraSocial;
import com.shoc.domain.ObraSocial;
import com.shoc.domain.service.ObraSocialService;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.text.JTextComponent;

/**
 *
 * @author diego
 */
public class ObraSocialCreacion extends javax.swing.JPanel implements IObraSocial {

    private ObraSocialService service = (ObraSocialService) ObraSocialService.getInstance();
    private Long obraSocialId = null;

    /**
     * Creates new form ObraSocialCreacion
     */
    public ObraSocialCreacion() {
        initComponents();
        initFields();
    }

    private List<Component> getAllComponents() {
        List panels = Arrays.asList(this.getComponents());
        List<Component> componentes = new ArrayList();
        for (Object panel : panels) {
            if (panel instanceof JPanel) {
                componentes.addAll(
                        Arrays.asList(((JPanel) panel).getComponents())
                );
            }
        }
        return componentes;
    }

    public ObraSocialCreacion(Long id, Boolean editable) {
        initComponents();

        initFields();

        for (Component comp : getAllComponents()) {
            if (comp instanceof JTextComponent) {
                ((JTextComponent) comp).setEditable(editable);
            }
        }

        if (!editable) {
            bGrabar.setText("Editar");
        }

        ObraSocial ob = this.service.get(id);

        // informacion general 
        this.obraSocialId = id;
        tfRazonSocial.setText(ob.getRazonSocial());
        tfCUIT.setText(ob.getCuit());
        tfResponsable.setText(ob.getResponsable());
        taRequerimiento.setText(ob.getRequerimiento());

        // Contacto
        tfCelular.setText(ob.getCelular());
        tfTelefono.setText(ob.getTelefono());
        tfEmail.setText(ob.getEmail());
        tfEmailWeb.setText(ob.getEmailWeb());

        // Costos
        tfCostoInternacion.setText(String.valueOf(ob.getCosto(DispositivosEnum.INTERNACION)));
        tfCostoJornadaCompleta.setText(String.valueOf(ob.getCosto(DispositivosEnum.HDJC)));
        tfCostoMediaJornada.setText(String.valueOf(ob.getCosto(DispositivosEnum.HDMC)));
        tfCostoAmbulatorio.setText(String.valueOf(ob.getCosto(DispositivosEnum.AMBULATORIO)));
        tfCosto5.setText(String.valueOf(ob.getCosto(DispositivosEnum.DISPOSITIVO)));

        tfFormaDePago.setText(ob.getFormaDePago());
        tfCategoriaIva.setText(ob.getCategoriaIva());
        cbModulo.setSelected(ob.getModulo());

        // Direccion
        tfDireccion.setText(ob.getDireccion());
        tfProvincia.setText(ob.getProvincia());
        tfLocalidad.setText(ob.getLocalidad());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tfCUIT = new RequiredTextfield();
        tfRazonSocial = new RequiredTextfield();
        lRazonSocial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taRequerimiento = new javax.swing.JTextArea();
        lCuit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfResponsable = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tfCelular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        tfEmailWeb = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tfCostoInternacion = new RequiredTextfield(true);
        lInternacion = new javax.swing.JLabel();
        tfCostoJornadaCompleta = new RequiredTextfield(true);
        lAmbulatorio = new javax.swing.JLabel();
        lMediaJornada = new javax.swing.JLabel();
        lJornadaCompleta = new javax.swing.JLabel();
        tfCostoAmbulatorio = new RequiredTextfield(true);
        tfCosto5 = new RequiredTextfield(true);
        jLabel18 = new javax.swing.JLabel();
        tfFormaDePago = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfCategoriaIva = new javax.swing.JTextField();
        cbModulo = new javax.swing.JCheckBox();
        tfCostoMediaJornada = new RequiredTextfield(true);
        ldispo5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        tfDireccion = new RequiredTextfield();
        tfProvincia = new RequiredTextfield();
        tfLocalidad = new RequiredTextfield();
        lDireccion = new javax.swing.JLabel();
        lLocalidad = new javax.swing.JLabel();
        lProvincia = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        bCancelar = new javax.swing.JButton();
        bGrabar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(715, 465));
        setMinimumSize(new java.awt.Dimension(715, 465));
        setPreferredSize(new java.awt.Dimension(716, 465));
        setRequestFocusEnabled(false);
        setSize(new java.awt.Dimension(716, 465));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));

        jLabel7.setText("Requerimiento:");

        tfCUIT.setNextFocusableComponent(tfResponsable);

        tfRazonSocial.setNextFocusableComponent(tfCUIT);

        lRazonSocial.setText("Razón Social:");

        taRequerimiento.setColumns(10);
        taRequerimiento.setLineWrap(true);
        taRequerimiento.setRows(2);
        taRequerimiento.setNextFocusableComponent(tfCelular);
        jScrollPane1.setViewportView(taRequerimiento);

        lCuit.setText("CUIT:");

        jLabel4.setText("Responsable:");

        tfResponsable.setNextFocusableComponent(taRequerimiento);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfRazonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(tfCUIT, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(tfResponsable))
                .addGap(10, 10, 10))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, lCuit, lRazonSocial});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRazonSocial)
                    .addComponent(lRazonSocial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCUIT)
                    .addComponent(lCuit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfResponsable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel7, lCuit, lRazonSocial});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Contacto"));

        jLabel11.setText("Email F. Web:");

        tfCelular.setNextFocusableComponent(tfTelefono);

        jLabel3.setText("Teléfono:");

        jLabel8.setText("Email:");

        tfEmail.setNextFocusableComponent(tfEmailWeb);

        tfTelefono.setNextFocusableComponent(tfEmail);

        tfEmailWeb.setNextFocusableComponent(tfCostoInternacion);

        jLabel2.setText("Celular:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(tfEmail)
                    .addComponent(tfTelefono)
                    .addComponent(tfEmailWeb))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel2, jLabel3, jLabel8});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCelular)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefono)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmailWeb)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Facturacion"));

        tfCostoInternacion.setNextFocusableComponent(tfCostoJornadaCompleta);

        lInternacion.setText("Internción:");

        tfCostoJornadaCompleta.setNextFocusableComponent(tfCostoMediaJornada);

        lAmbulatorio.setText("Ambulatorio:");

        lMediaJornada.setText("Media jornada:");

        lJornadaCompleta.setText("Jornada completa:");

        tfCostoAmbulatorio.setNextFocusableComponent(tfCosto5);

        tfCosto5.setNextFocusableComponent(tfFormaDePago);

        jLabel18.setText("Forma de pago:");

        tfFormaDePago.setNextFocusableComponent(tfCategoriaIva);

        jLabel19.setText("Categoria Iva:");

        tfCategoriaIva.setNextFocusableComponent(cbModulo);

        cbModulo.setText("Modulo");
        cbModulo.setNextFocusableComponent(tfDireccion);
        cbModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbModuloActionPerformed(evt);
            }
        });

        tfCostoMediaJornada.setNextFocusableComponent(tfCostoAmbulatorio);
        tfCostoMediaJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCostoMediaJornadaActionPerformed(evt);
            }
        });

        ldispo5.setText("Consultorio Externo:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(cbModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ldispo5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lInternacion, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lJornadaCompleta, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lMediaJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lAmbulatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCostoJornadaCompleta)
                            .addComponent(tfCostoMediaJornada)
                            .addComponent(tfCostoAmbulatorio)
                            .addComponent(tfCosto5)
                            .addComponent(tfFormaDePago)
                            .addComponent(tfCategoriaIva)
                            .addComponent(tfCostoInternacion, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel18, jLabel19, lAmbulatorio, lInternacion, lJornadaCompleta, lMediaJornada, ldispo5});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCostoInternacion)
                    .addComponent(lInternacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCostoJornadaCompleta)
                    .addComponent(lJornadaCompleta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCostoMediaJornada)
                    .addComponent(lMediaJornada))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCostoAmbulatorio)
                    .addComponent(lAmbulatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCosto5)
                    .addComponent(ldispo5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFormaDePago)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tfCategoriaIva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbModulo)
                .addGap(0, 0, 0))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Domicilio"));

        tfDireccion.setNextFocusableComponent(tfProvincia);

        tfProvincia.setNextFocusableComponent(lLocalidad);

        tfLocalidad.setNextFocusableComponent(tfLocalidad);

        lDireccion.setText("Dirección:");
        lDireccion.setMaximumSize(new java.awt.Dimension(86, 16));
        lDireccion.setMinimumSize(new java.awt.Dimension(86, 16));

        lLocalidad.setText("Localidad:");

        lProvincia.setText("Provincia:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(tfLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addGap(1, 1, 1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))))
                .addGap(8, 8, 8))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDireccion)
                    .addComponent(lDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProvincia)
                    .addComponent(lProvincia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLocalidad)
                    .addComponent(lLocalidad))
                .addContainerGap())
        );

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bGrabar.setText("Grabar");
        bGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGrabarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(bCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGrabarActionPerformed
        if (bGrabar.getText().equals("Editar")) {
            for (Component comp : getAllComponents()) {
                comp.setEnabled(true);
            }
            bGrabar.setText("Grabar");
        } else {
            Boolean valido = this.validarFormulario();

            if (valido) {
                service.createObraSocial(this);

                mainFrame topFrame = (mainFrame) SwingUtilities.getWindowAncestor(this);
                topFrame.changePanel(new ObraSocialList(), this);
            }
        }
    }//GEN-LAST:event_bGrabarActionPerformed

    private Boolean validarFormulario() {
        Boolean valid = true;
        List componentes = getAllComponents();

        for (Object componente : componentes) {
            if (componente instanceof IValidable) {
                valid = ((IValidable) componente).valid() && valid;
            }
        }

        if (!valid) {
            mainFrame topFrame = (mainFrame) SwingUtilities.getWindowAncestor(this);
            JOptionPane.showMessageDialog(topFrame, "Por favor complete los campos requeridos.", "Campos requeridos", JOptionPane.ERROR_MESSAGE);

        }

        return valid;
    }

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        mainFrame topFrame = (mainFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.changePanel(new ObraSocialList(), this);
    }//GEN-LAST:event_bCancelarActionPerformed

    private void cbModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbModuloActionPerformed

    private void tfCostoMediaJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCostoMediaJornadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCostoMediaJornadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bGrabar;
    private javax.swing.JCheckBox cbModulo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAmbulatorio;
    private javax.swing.JLabel lCuit;
    private javax.swing.JLabel lDireccion;
    private javax.swing.JLabel lInternacion;
    private javax.swing.JLabel lJornadaCompleta;
    private javax.swing.JLabel lLocalidad;
    private javax.swing.JLabel lMediaJornada;
    private javax.swing.JLabel lProvincia;
    private javax.swing.JLabel lRazonSocial;
    private javax.swing.JLabel ldispo5;
    private javax.swing.JTextArea taRequerimiento;
    private javax.swing.JTextField tfCUIT;
    private javax.swing.JTextField tfCategoriaIva;
    private javax.swing.JTextField tfCelular;
    private javax.swing.JTextField tfCosto5;
    private javax.swing.JTextField tfCostoAmbulatorio;
    private javax.swing.JTextField tfCostoInternacion;
    private javax.swing.JTextField tfCostoJornadaCompleta;
    private javax.swing.JTextField tfCostoMediaJornada;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEmailWeb;
    private javax.swing.JTextField tfFormaDePago;
    private javax.swing.JTextField tfLocalidad;
    private javax.swing.JTextField tfProvincia;
    private javax.swing.JTextField tfRazonSocial;
    private javax.swing.JTextField tfResponsable;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getCuit() {
        return tfCUIT.getText();
    }

    @Override
    public Long getId() {
        return obraSocialId;
    }

    @Override
    public String getRazonSocial() {
        return tfRazonSocial.getText();
    }

    @Override
    public String getResponsable() {
        return tfResponsable.getText();
    }

    @Override
    public String getRequerimiento() {
        return taRequerimiento.getText();
    }

    @Override
    public String getCelular() {
        return tfCelular.getText();
    }

    @Override
    public String getTelefono() {
        return tfTelefono.getText();
    }

    @Override
    public String getEmail() {
        return tfEmail.getText();
    }

    @Override
    public String getEmailWeb() {
        return tfEmailWeb.getText();
    }

    @Override
    public Double getCostoInternacion() {
        return Double.valueOf(tfCostoInternacion.getText());
    }

    @Override
    public Double getCostoJornadaCompleta() {
        return Double.valueOf(tfCostoJornadaCompleta.getText());

    }

    @Override
    public Double getCostoMediaJornada() {
        return Double.valueOf(tfCostoMediaJornada.getText());
    }

    @Override
    public Double getCostoAmbulatorio() {
        return Double.valueOf(tfCostoAmbulatorio.getText());
    }

    @Override
    public Double getCosto5() {
        return Double.valueOf(tfCosto5.getText());
    }

    @Override
    public String getFormaDePago() {
        return tfFormaDePago.getText();
    }

    @Override
    public String getCategoriaIva() {
        return tfCategoriaIva.getText();
    }

    @Override
    public Boolean getModulo() {
        return cbModulo.isSelected();
    }

    @Override
    public String getDireccion() {
        return tfDireccion.getText();
    }

    @Override
    public String getProvincia() {
        return tfProvincia.getText();
    }

    @Override
    public String getLocalidad() {
        return tfLocalidad.getText();
    }

    private void initFields() {
        ((IValidable) this.tfRazonSocial).setLabel(lRazonSocial);
        ((IValidable) this.tfCUIT).setLabel(lCuit);

        ((IValidable) this.tfDireccion).setLabel(lDireccion);
        ((IValidable) this.tfProvincia).setLabel(lProvincia);
        ((IValidable) this.tfLocalidad).setLabel(lLocalidad);

        ((IValidable) this.tfCostoInternacion).setLabel(lInternacion);
        ((IValidable) this.tfCosto5).setLabel(ldispo5);
        ((IValidable) this.tfCostoAmbulatorio).setLabel(lAmbulatorio);
        ((IValidable) this.tfCostoJornadaCompleta).setLabel(lJornadaCompleta);
        ((IValidable) this.tfCostoMediaJornada).setLabel(lMediaJornada);
    }
}
