/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shoc.controller.Panels;

import com.shoc.domain.IObraSocial;
import com.shoc.domain.service.ObraSocialService;
import java.awt.Component;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author diego
 */
public class ObraSocialCreacion extends javax.swing.JPanel implements IObraSocial {

    private ObraSocialService service = (ObraSocialService) ObraSocialService.getInstance();
    private Long obraSocialId = null;

    /**
     * Creates new form ObraSocialCreacion
     */
    public ObraSocialCreacion() {
        initComponents();
    }

    public ObraSocialCreacion(Long id, Boolean editable) {
        initComponents();

        for (Component comp : this.getComponents()) {
            if (comp instanceof JTextField) {
                ((JTextField) comp).setEditable(editable);
            }
        }

        if (!editable) {
            bGrabar.setText("Editar");
        }

        IObraSocial ob = this.service.get(id);

        // informacion general 
        this.obraSocialId = id;
        tfRazonSocial.setText(ob.getRazonSocial());
        tfCUIT.setText(ob.getCuit());
        tfResponsable.setText(ob.getResponsable());
        taRequerimiento.setText(ob.getRequerimiento());

        // Contacto
        tfCelular.setText(ob.getCelular());
        tfTelefono.setText(ob.getTelefono());
        tfEmail.setText(ob.getEmail());
        tfEmailWeb.setText(ob.getEmailWeb());

        // Costos
        tfCostoInternacion.setText(ob.getCostoInternacion().toString());
        tfCostoJornadaCompleta.setText(ob.getCostoJornadaCompleta().toString());
        tfCostoMediaJornada.setText(ob.getCostoMediaJornada().toString());
        tfCostoAmbulatorio.setText(ob.getCostoAmbulatorio().toString());
        tfCosto5.setText(ob.getCosto5().toString());
        tfFormaDePago.setText(ob.getFormaDePago());
        tfCategoriaIva.setText(ob.getCategoriaIva());
        cbModulo.setSelected(ob.getModulo());

        // Direccion
        tfDireccion.setText(ob.getDireccion());
        tfProvincia.setText(ob.getProvincia());
        tfLocalidad.setText(ob.getLocalidad());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfRazonSocial = new javax.swing.JTextField();
        tfCUIT = new javax.swing.JTextField();
        bGrabar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfResponsable = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfCelular = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taRequerimiento = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfEmailWeb = new javax.swing.JTextField();
        tfCostoInternacion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfCostoJornadaCompleta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfCostoMediaJornada = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfCostoAmbulatorio = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfCosto5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfFormaDePago = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfCategoriaIva = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        tfProvincia = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfLocalidad = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        bCancelar = new javax.swing.JButton();
        cbModulo = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(715, 465));
        setMinimumSize(new java.awt.Dimension(715, 465));
        setPreferredSize(new java.awt.Dimension(716, 465));
        setRequestFocusEnabled(false);
        setSize(new java.awt.Dimension(716, 465));

        tfRazonSocial.setNextFocusableComponent(tfCUIT);

        tfCUIT.setNextFocusableComponent(tfResponsable);

        bGrabar.setText("Grabar");
        bGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGrabarActionPerformed(evt);
            }
        });

        jLabel1.setText("Razon Social:");

        jLabel2.setText("Celular:");

        jLabel3.setText("Telefono:");

        jLabel4.setText("Responsable:");

        jLabel5.setText("Interncion:");

        jLabel6.setText("CUIT:");

        tfResponsable.setNextFocusableComponent(taRequerimiento);

        jLabel7.setText("Requerimiento:");

        tfCelular.setNextFocusableComponent(tfTelefono);

        tfTelefono.setNextFocusableComponent(tfEmail);

        jLabel8.setText("Email:");

        tfEmail.setNextFocusableComponent(tfEmailWeb);

        taRequerimiento.setColumns(20);
        taRequerimiento.setRows(5);
        taRequerimiento.setNextFocusableComponent(tfCelular);
        jScrollPane1.setViewportView(taRequerimiento);

        jLabel9.setText("Contacto:");

        jLabel10.setText("General:");

        jLabel11.setText("Email F. Web:");

        tfEmailWeb.setNextFocusableComponent(tfCostoInternacion);

        tfCostoInternacion.setNextFocusableComponent(tfCostoJornadaCompleta);

        jLabel12.setText("Jornada completa:");

        tfCostoJornadaCompleta.setNextFocusableComponent(tfCostoMediaJornada);

        jLabel13.setText("Media jornada:");

        tfCostoMediaJornada.setNextFocusableComponent(tfCostoAmbulatorio);

        jLabel15.setText("Ambulatorio:");

        tfCostoAmbulatorio.setNextFocusableComponent(tfCosto5);

        jLabel16.setText("Dipositivo 5:");

        tfCosto5.setNextFocusableComponent(tfFormaDePago);

        jLabel18.setText("Foma de pago:");

        tfFormaDePago.setNextFocusableComponent(tfCategoriaIva);

        jLabel19.setText("Categoria Iva:");

        tfCategoriaIva.setNextFocusableComponent(cbModulo);

        jLabel14.setText("Costos:");

        tfDireccion.setNextFocusableComponent(tfDireccion);

        tfProvincia.setNextFocusableComponent(tfProvincia);

        jLabel20.setText("Localidad:");

        tfLocalidad.setNextFocusableComponent(tfLocalidad);

        jLabel21.setText("Domicilio:");

        jLabel22.setText("Direccion:");
        jLabel22.setMaximumSize(new java.awt.Dimension(86, 16));
        jLabel22.setMinimumSize(new java.awt.Dimension(86, 16));

        jLabel23.setText("Provincia:");

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        cbModulo.setText("Modulo");
        cbModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbModuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCUIT, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfEmailWeb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCelular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(cbModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(111, 111, 111))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfCostoJornadaCompleta, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                            .addComponent(tfCostoMediaJornada)
                                            .addComponent(tfCostoAmbulatorio)
                                            .addComponent(tfCosto5)
                                            .addComponent(tfFormaDePago)
                                            .addComponent(tfCategoriaIva)
                                            .addComponent(tfCostoInternacion)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(tfLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)))
                                .addContainerGap(19, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, tfCUIT, tfCelular, tfEmail, tfEmailWeb, tfRazonSocial, tfResponsable, tfTelefono});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel12, jLabel13, jLabel15, jLabel16, jLabel18, jLabel19, jLabel5});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel2, jLabel3, jLabel8});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel4, jLabel6});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfDireccion, tfLocalidad, tfProvincia});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCostoInternacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCostoJornadaCompleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCostoMediaJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCostoAmbulatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCosto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfFormaDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(tfCategoriaIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbModulo)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCUIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEmailWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGrabar)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfCUIT, tfCelular, tfEmail, tfEmailWeb, tfRazonSocial, tfResponsable, tfTelefono});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel11, jLabel2, jLabel3, jLabel4, jLabel6, jLabel7, jLabel8});

    }// </editor-fold>//GEN-END:initComponents

    private void bGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGrabarActionPerformed
        if (bGrabar.getText().equals("Editar")) {
            for (Component comp : this.getComponents()) {
                if (comp instanceof JTextField) {
                    ((JTextField) comp).setEditable(true);
                }
            }
            bGrabar.setText("Grabar");
        } else {
            service.createObraSocial(this);

            mainFrame topFrame = (mainFrame) SwingUtilities.getWindowAncestor(this);
            topFrame.changePanel(new ObraSocialList(), this);
        }
    }//GEN-LAST:event_bGrabarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        mainFrame topFrame = (mainFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.changePanel(new ObraSocialList(), this);
    }//GEN-LAST:event_bCancelarActionPerformed

    private void cbModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbModuloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bGrabar;
    private javax.swing.JCheckBox cbModulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taRequerimiento;
    private javax.swing.JTextField tfCUIT;
    private javax.swing.JTextField tfCategoriaIva;
    private javax.swing.JTextField tfCelular;
    private javax.swing.JTextField tfCosto5;
    private javax.swing.JTextField tfCostoAmbulatorio;
    private javax.swing.JTextField tfCostoInternacion;
    private javax.swing.JTextField tfCostoJornadaCompleta;
    private javax.swing.JTextField tfCostoMediaJornada;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEmailWeb;
    private javax.swing.JTextField tfFormaDePago;
    private javax.swing.JTextField tfLocalidad;
    private javax.swing.JTextField tfProvincia;
    private javax.swing.JTextField tfRazonSocial;
    private javax.swing.JTextField tfResponsable;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getCuit() {
        return tfCUIT.getText();
    }

    @Override
    public Long getId() {
        return obraSocialId;
    }

    @Override
    public String getRazonSocial() {
        return tfRazonSocial.getText();
    }

    @Override
    public String getResponsable() {
        return tfResponsable.getText();
    }

    @Override
    public String getRequerimiento() {
        return taRequerimiento.getText();
    }

    @Override
    public String getCelular() {
        return tfCelular.getText();
    }

    @Override
    public String getTelefono() {
        return tfTelefono.getText();
    }

    @Override
    public String getEmail() {
        return tfEmail.getText();
    }

    @Override
    public String getEmailWeb() {
        return tfEmailWeb.getText();
    }

    @Override
    public Double getCostoInternacion() {
        return Double.valueOf(tfCostoInternacion.getText());
    }

    @Override
    public Double getCostoJornadaCompleta() {
        return Double.valueOf(tfCostoJornadaCompleta.getText());

    }

    @Override
    public Double getCostoMediaJornada() {
        return Double.valueOf(tfCostoMediaJornada.getText());
    }

    @Override
    public Double getCostoAmbulatorio() {
        return Double.valueOf(tfCostoAmbulatorio.getText());
    }

    @Override
    public Double getCosto5() {
        return Double.valueOf(tfCosto5.getText());
    }

    @Override
    public String getFormaDePago() {
        return tfFormaDePago.getText();
    }

    @Override
    public String getCategoriaIva() {
        return tfCategoriaIva.getText();
    }

    @Override
    public Boolean getModulo() {
        return cbModulo.isSelected();
    }

    @Override
    public String getDireccion() {
        return tfDireccion.getText();
    }

    @Override
    public String getProvincia() {
        return tfProvincia.getText();
    }

    @Override
    public String getLocalidad() {
        return tfLocalidad.getText();
    }
}
